### ISSUE TITLE
ARM64 Android Version

### ISSUE THREAD

**Issue by Hanzy0000** [marcussacana/DirectPackageInstaller#68]
I'm using an android version for this program with Android 14 OS and the app crashes immediately when all the pop ups were removed.

**Comment by marcussacana** [comment]
The android popup any error log?
Check in your \Android\ folder if a Crash.log file is created.

**Comment by Hanzy0000** [comment]
No, it just crashes immediately after it introduces the function of the  and all its appendices

**Comment by Hanzy0000** [comment]
No, it just crashes immediately after all the introductions were closed.

https://github.com/user-attachments/assets/2fcec9a4-5c5f-4a8a-beb7-283db7931e5a

Look at this recording for reference.

If what you said is still the solution for that, i don't know how to do it because in android 14 now can't access the data folders of the applications

**Comment by marcussacana** [comment]
You should be able to access if install the google file manager.

**Comment by Hanzy0000** [comment]
Yes, the crash log file is created

**Comment by marcussacana** [comment]
upload it here, or just copy the content and paste it.

**Comment by Hanzy0000** [comment]
Java.Lang.IllegalArgumentException: com.marcussacana.DirectPackageInstaller: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String , JniArgumentValue* )
   at Android.App.PendingIntent.GetBroadcast(Context , Int32 , Intent , PendingIntentFlags )
   at DirectPackageInstaller.Android.ForegroundService.BindForeground()
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: com.marcussacana.DirectPackageInstaller: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:435)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:748)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:735)
	at crc645ecd3e76dd4f46d2.ForegroundService.n_onStartCommand(Native Method)
	at crc645ecd3e76dd4f46d2.ForegroundService.onStartCommand(ForegroundService.java:39)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: com.marcussacana.DirectPackageInstaller: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:435)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:748)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:735)
	at crc645ecd3e76dd4f46d2.ForegroundService.n_onStartCommand(Native Method)
	at crc645ecd3e76dd4f46d2.ForegroundService.onStartCommand(ForegroundService.java:39)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by Hanzy0000** [comment]
[DPI-AndroidCrash.log](https://github.com/user-attachments/files/18276589/DPI-AndroidCrash.log)
